/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable react-hooks/purity */
"use client";

import React, { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { getStroke } from "perfect-freehand";
import { getStorageKey } from "@/lib/storage";

type Point = {
    x: number;
    y: number;
    timestamp: number;
    pressure?: number;
};

type Stroke = {
    id: string;
    tool: "pencil" | "eraser";
    color: string;
    size: number;
    points: Point[];
    smoothing: boolean;
};

// Define colors and sizes
const COLORS = [
    "#ffffff", // White
    "#000000", // Black
    "#ef4444", // Red
    "#f59e0b", // Orange/Gold
    "#eab308", // Yellow
    "#10b981", // Green
    "#3b82f6", // Blue
    "#8b5cf6", // Purple
    "#ec4899", // Pink
];
const SIZES = [2, 5, 10, 20, 30];

// Helper to draw the complex polygon generated by perfect-freehand
function getSvgPathFromStroke(stroke: number[][]) {
    if (!stroke.length) return "";
    const d = stroke.reduce(
        (acc, [x0, y0], i, arr) => {
            const [x1, y1] = arr[(i + 1) % arr.length];
            acc.push(x0, y0, (x0 + x1) / 2, (y0 + y1) / 2);
            return acc;
        },
        ["M", ...stroke[0], "Q"]
    );
    d.push("Z");
    return d.join(" ");
}

export default function DrawingBoard() {
    const containerRef = useRef<HTMLDivElement>(null);
    const canvasRef = useRef<HTMLCanvasElement>(null);

    // Tools & State
    const [isDrawing, setIsDrawing] = useState(false);
    const [currentTool, setCurrentTool] = useState<"pencil" | "eraser">("pencil");
    const [currentColor, setCurrentColor] = useState(COLORS[0]);
    const [currentSize, setCurrentSize] = useState(SIZES[1]);

    // Storage
    const [strokes, setStrokes] = useState<Stroke[]>([]);
    const [currentStroke, setCurrentStroke] = useState<Stroke | null>(null);

    // Assistants
    const [useSmoothing, setUseSmoothing] = useState(false);
    const [useSymmetry, setUseSymmetry] = useState(false);
    const [showAssistants, setShowAssistants] = useState(false);

    // Setup Canvas Resolution
    useEffect(() => {
        const resizeCanvas = () => {
            if (canvasRef.current && containerRef.current) {
                const { clientWidth, clientHeight } = containerRef.current;
                const dpr = window.devicePixelRatio || 1;
                canvasRef.current.width = clientWidth * dpr;
                canvasRef.current.height = clientHeight * dpr;

                // Reset transform and clear
                const ctx = canvasRef.current.getContext("2d");
                if (ctx) {
                    ctx.setTransform(1, 0, 0, 1, 0, 0);
                    ctx.scale(dpr, dpr);
                }
                redrawAll();
            }
        };
        window.addEventListener("resize", resizeCanvas);
        resizeCanvas();
        return () => window.removeEventListener("resize", resizeCanvas);
    }, []);

    // Redraw Hook
    useEffect(() => {
        redrawAll();
    }, [strokes, currentStroke, useSymmetry]);

    // Main Render Logic
    function redrawAll() {
        const canvas = canvasRef.current;
        if (!canvas) return;
        const ctx = canvas.getContext("2d");
        if (!ctx) return;

        // Clear background
        ctx.save();
        ctx.setTransform(1, 0, 0, 1, 0, 0);
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        // Dark background matching layout
        ctx.fillStyle = "#0f0a1e";
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        ctx.restore();

        // Draw symmetry line
        if (useSymmetry) {
            ctx.beginPath();
            ctx.moveTo(canvas.width / 2 / (window.devicePixelRatio || 1), 0);
            ctx.lineTo(canvas.width / 2 / (window.devicePixelRatio || 1), canvas.height / (window.devicePixelRatio || 1));
            ctx.strokeStyle = "rgba(124, 58, 237, 0.2)"; // quest-purple faint
            ctx.setLineDash([10, 10]);
            ctx.stroke();
            ctx.setLineDash([]);
        }

        const allStrokes = currentStroke ? [...strokes, currentStroke] : strokes;
        const canvasLogicWidth = canvas.width / (window.devicePixelRatio || 1);

        allStrokes.forEach((stroke) => {
            if (stroke.points.length === 0) return;

            // Determine rendering path (perfect-freehand vs raw points)
            let pathData: number[][] = [];

            if (stroke.smoothing) {
                // Advanced smoothing with perfect-freehand
                pathData = getStroke(stroke.points, {
                    size: stroke.size,
                    thinning: 0.5,
                    smoothing: 0.5,
                    streamline: 0.5,
                });
            } else {
                // Basic raw point drawing but wrapped in perfect-freehand for consistent SVG generation
                pathData = getStroke(stroke.points, {
                    size: stroke.size,
                    thinning: 0,
                    smoothing: 0,
                    streamline: 0,
                });
            }

            const pathString = getSvgPathFromStroke(pathData);

            // Setup Style
            ctx.fillStyle = stroke.tool === "eraser" ? "#0f0a1e" : stroke.color;
            const path = new Path2D(pathString);
            ctx.fill(path);

            // Render Symmetry Stroke if enabled (mirror X across center)
            if (useSymmetry && stroke.tool === "pencil") { // Check explicitly for pencil to avoid TS overlap errors and logic flaws
                const mirroredPoints = stroke.points.map(p => ({
                    ...p,
                    x: canvasLogicWidth - p.x
                }));

                let mirrorPathData: number[][] = [];
                if (stroke.smoothing) {
                    mirrorPathData = getStroke(mirroredPoints, { size: stroke.size, thinning: 0.5, smoothing: 0.5, streamline: 0.5 });
                } else {
                    mirrorPathData = getStroke(mirroredPoints, { size: stroke.size, thinning: 0, smoothing: 0, streamline: 0 });
                }

                const mirrorPathString = getSvgPathFromStroke(mirrorPathData);
                ctx.fillStyle = stroke.color;
                ctx.fill(new Path2D(mirrorPathString));
            }
        });
    };

    const getCoordinates = (e: React.PointerEvent<HTMLCanvasElement>) => {
        if (!canvasRef.current) return { x: 0, y: 0, pressure: 0.5 };
        const rect = canvasRef.current.getBoundingClientRect();
        return {
            x: e.clientX - rect.left,
            y: e.clientY - rect.top,
            pressure: e.pressure > 0 ? e.pressure : 0.5 // Fallback if no pressure reported
        };
    };

    const handlePointerDown = (e: React.PointerEvent<HTMLCanvasElement>) => {
        if (e.pointerType === "mouse" && e.button !== 0) return;
        (e.target as Element).setPointerCapture(e.pointerId);

        setIsDrawing(true);
        const coords = getCoordinates(e);
        const newStroke: Stroke = {
            id: Date.now().toString(),
            tool: currentTool,
            color: currentColor,
            size: currentSize,
            points: [{ ...coords, timestamp:  Date.now() }],
            smoothing: useSmoothing, // lock in the current smoothing setting for this stroke
        };
        setCurrentStroke(newStroke);
    };

    const handlePointerMove = (e: React.PointerEvent<HTMLCanvasElement>) => {
        // Only capture movement while drawing or if pressure exists (stylus hover handling)
        if (!isDrawing || !currentStroke) return;

        // Optional: Only record point if e.buttons === 1 to handle cases where mouse up escapes div
        if (e.pointerType === "mouse" && e.buttons !== 1) {
            handlePointerUp(e);
            return;
        }

        const coords = getCoordinates(e);
        setCurrentStroke({
            ...currentStroke,
            points: [...currentStroke.points, { ...coords, timestamp:  Date.now() }],
        });
    };

    const handlePointerUp = (e: React.PointerEvent<HTMLCanvasElement>) => {
        if (!isDrawing || !currentStroke) return;
        (e.target as Element).releasePointerCapture(e.pointerId);
        setIsDrawing(false);
        setStrokes((prev) => [...prev, currentStroke]);
        setCurrentStroke(null);
    };

    const exportMetadata = () => {
        const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(strokes));
        const a = document.createElement("a");
        a.href = dataStr;
        a.download = "alice_art_metadata.json";
        document.body.appendChild(a);
        a.click();
        a.remove();
    };

    const saveToGallery = () => {
        if (!canvasRef.current) return;
        // Convert canvas to Data URL for thumbnail
        const thumbnailDataUrl = canvasRef.current.toDataURL("image/png");
        const drawingData = {
            id: Date.now().toString(),
            timestamp: new Date().toISOString(),
            thumbnail: thumbnailDataUrl,
            strokes: strokes
        };

        const existing = localStorage.getItem(getStorageKey("alice_gallery"));
        const gallery = existing ? JSON.parse(existing) : [];
        gallery.push(drawingData);
        localStorage.setItem(getStorageKey("alice_gallery"), JSON.stringify(gallery));
        alert("Disegno salvato in Galleria!");
    };

    const clearCanvas = () => {
        if (confirm("Sei sicuro di voler cancellare tutto?")) {
            setStrokes([]);
            setCurrentStroke(null);
        }
    };

    return (
        <div className="flex flex-col h-screen w-full bg-[#0f0a1e] relative text-white" ref={containerRef}>

            {}
            <div className="absolute top-4 left-4 z-20">
                <Link href="/" className="btn-secondary text-xs backdrop-blur-md bg-[#1e1535]/50">
                    ⬅ Menu
                </Link>
            </div>

            <canvas
                ref={canvasRef}
                onPointerDown={handlePointerDown}
                onPointerMove={handlePointerMove}
                onPointerUp={handlePointerUp}
                onPointerCancel={handlePointerUp}
                className="w-full h-full cursor-crosshair touch-none z-10 block"
            />

            {}
            <div className="absolute bottom-4 sm:bottom-6 left-1/2 -translate-x-1/2 w-[95%] sm:w-auto bg-[#1e1535]/95 backdrop-blur-xl p-2 sm:p-3 rounded-2xl border border-[#3b2d6e] shadow-2xl flex flex-wrap justify-center items-center gap-2 sm:gap-4 z-20 overflow-visible">

                {}
                <div className="flex bg-black/40 p-1 rounded-xl">
                    <button
                        onClick={() => setCurrentTool("pencil")}
                        className={`p-2 sm:p-3 rounded-lg flex items-center justify-center transition-all ${currentTool === "pencil" ? "bg-purple-600 shadow-[0_0_15px_rgba(147,51,234,0.5)]" : "hover:bg-white/10"}`}
                        title="Matita"
                    >
                        <span className="text-sm sm:text-base">✏️</span>
                    </button>
                    <button
                        onClick={() => setCurrentTool("eraser")}
                        className={`p-2 sm:p-3 rounded-lg flex items-center justify-center transition-all ${currentTool === "eraser" ? "bg-pink-600 shadow-[0_0_15px_rgba(236,72,153,0.5)]" : "hover:bg-white/10"}`}
                        title="Gomma"
                    >
                        <span className="text-sm sm:text-base">🧽</span>
                    </button>
                </div>

                {}
                <div className="flex gap-1.5 sm:gap-2 items-center flex-wrap justify-center max-w-[120px] sm:max-w-none">
                    {COLORS.map((color) => (
                        <button
                            key={color}
                            onClick={() => { setCurrentColor(color); setCurrentTool("pencil"); }}
                            className={`w-6 h-6 sm:w-8 sm:h-8 rounded-full transition-transform ${currentColor === color && currentTool !== "eraser" ? "scale-125 ring-2 ring-white" : "hover:scale-110"}`}
                            style={{ backgroundColor: color }}
                            title={color}
                        />
                    ))}
                </div>

                <div className="w-[1px] h-8 sm:h-10 bg-[#3b2d6e] hidden sm:block"></div>

                {}
                <div className="flex items-center gap-1.5 sm:gap-2">
                    {SIZES.map((size) => (
                        <button
                            key={size}
                            onClick={() => setCurrentSize(size)}
                            className={`flex items-center justify-center w-6 h-6 sm:w-8 sm:h-8 rounded-full transition-all ${currentSize === size ? "bg-purple-600 focus:outline-none" : "bg-white/5 hover:bg-white/15"}`}
                        >
                            <div className="bg-white rounded-full pointer-events-none" style={{ width: Math.max(2, size / 3), height: Math.max(2, size / 3) }} />
                        </button>
                    ))}
                </div>

                <div className="w-[1px] h-8 sm:h-10 bg-[#3b2d6e] hidden sm:block"></div>

                {}
                <div className="relative">
                    <button
                        onClick={() => setShowAssistants(!showAssistants)}
                        className={`p-1.5 sm:p-2 rounded-lg transition-colors border ${showAssistants ? 'bg-purple-600/30 border-purple-400' : 'bg-transparent border-[#3b2d6e] hover:bg-white/5'}`}
                        title="Assistenti Intelligenti"
                    >
                        <span className="text-sm sm:text-base">🤖</span>
                    </button>
                    {showAssistants && (
                        <div className="absolute bottom-full mb-3 sm:mb-4 left-1/2 -translate-x-1/2 bg-[#1e1535] border border-purple-500/50 p-3 sm:p-4 rounded-xl shadow-[0_0_30px_rgba(124,58,237,0.3)] min-w-[180px] sm:min-w-[200px] flex flex-col gap-2 sm:gap-3 z-50">
                            <h4 className="text-[10px] sm:text-xs uppercase text-purple-400 font-bold mb-1">Assistenti IA</h4>

                            <label className="flex items-center justify-between cursor-pointer group">
                                <span className="text-xs sm:text-sm">Ammorbidisci Tratto</span>
                                <input type="checkbox" className="sr-only" checked={useSmoothing} onChange={(e) => setUseSmoothing(e.target.checked)} />
                                <div className={`w-8 sm:w-10 h-5 sm:h-6 rounded-full transition-colors relative ${useSmoothing ? 'bg-green-500' : 'bg-gray-700'}`}>
                                    <div className={`absolute top-0.5 sm:top-1 left-0.5 sm:left-1 bg-white w-4 h-4 rounded-full transition-transform ${useSmoothing ? 'translate-x-3 sm:translate-x-4' : ''}`}></div>
                                </div>
                            </label>

                            <label className="flex items-center justify-between cursor-pointer group">
                                <span className="text-xs sm:text-sm">Effetto Specchio X</span>
                                <input type="checkbox" className="sr-only" checked={useSymmetry} onChange={(e) => setUseSymmetry(e.target.checked)} />
                                <div className={`w-8 sm:w-10 h-5 sm:h-6 rounded-full transition-colors relative ${useSymmetry ? 'bg-blue-500' : 'bg-gray-700'}`}>
                                    <div className={`absolute top-0.5 sm:top-1 left-0.5 sm:left-1 bg-white w-4 h-4 rounded-full transition-transform ${useSymmetry ? 'translate-x-3 sm:translate-x-4' : ''}`}></div>
                                </div>
                            </label>
                        </div>
                    )}
                </div>

                <div className="w-[1px] h-8 sm:h-10 bg-[#3b2d6e] hidden sm:block"></div>

                {}
                <div className="flex gap-1.5 sm:gap-2">
                    <button onClick={clearCanvas} className="p-1.5 sm:p-2 sm:px-4 rounded-lg bg-red-500/20 text-red-400 font-medium border border-red-500/30 text-xs sm:text-base flex items-center justify-center" title="Cancella Tutto">
                        <span>🗑️</span>
                    </button>
                    <button onClick={exportMetadata} className="p-1.5 sm:p-2 sm:px-4 rounded-lg bg-purple-600/30 text-purple-300 font-medium border border-purple-600/50 text-xs sm:text-base" title="Scarica Metadati Jason">
                        <span className="hidden sm:inline">💾 JS</span>
                        <span className="sm:hidden">💾</span>
                    </button>
                    <button onClick={saveToGallery} className="p-1.5 sm:p-2 sm:px-4 rounded-lg bg-emerald-600 text-white font-medium shadow-[0_0_15px_rgba(16,185,129,0.4)] hover:bg-emerald-500 transition-colors text-xs sm:text-base" title="Salva in Galleria">
                        <span className="hidden sm:inline">Salva</span>
                        <span className="sm:hidden">✓</span>
                    </button>
                </div>

            </div>
        </div>
    );
}
